/*
 * This file is generated by jOOQ.
 */
package com.kbalazsworks.tictactoe.db;


import com.kbalazsworks.tictactoe.db.tables.FlywaySchemaHistory;
import com.kbalazsworks.tictactoe.db.tables.Game;
import com.kbalazsworks.tictactoe.db.tables.records.FlywaySchemaHistoryRecord;
import com.kbalazsworks.tictactoe.db.tables.records.GameRecord;

import org.jooq.Identity;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<GameRecord, Long> IDENTITY_GAME = Identities0.IDENTITY_GAME;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = UniqueKeys0.FLYWAY_SCHEMA_HISTORY_PK;
    public static final UniqueKey<GameRecord> GAME_PK = UniqueKeys0.GAME_PK;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<GameRecord, Long> IDENTITY_GAME = Internal.createIdentity(Game.GAME, Game.GAME.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, "flyway_schema_history_pk", new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
        public static final UniqueKey<GameRecord> GAME_PK = Internal.createUniqueKey(Game.GAME, "game_pk", new TableField[] { Game.GAME.ID }, true);
    }
}
