/*
 * This file is generated by jOOQ.
 */
package com.kbalazsworks.tictactoe.db;


import com.kbalazsworks.tictactoe.db.tables.FlywaySchemaHistory;
import com.kbalazsworks.tictactoe.db.tables.Game;
import com.kbalazsworks.tictactoe.db.tables.GameState;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1179247336;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.game</code>.
     */
    public final Game GAME = Game.GAME;

    /**
     * The table <code>public.game_state</code>.
     */
    public final GameState GAME_STATE = GameState.GAME_STATE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.GAME_ID_SEQ,
            Sequences.GAME_STATE_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Game.GAME,
            GameState.GAME_STATE);
    }
}
