/*
 * This file is generated by jOOQ.
 */
package com.kbalazsworks.tictactoe.db;


import org.jooq.Sequence;
import org.jooq.impl.Internal;


/**
 * Convenience access to all sequences in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.game_id_seq</code>
     */
    public static final Sequence<Long> GAME_ID_SEQ = Internal.createSequence("game_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.game_state_id_seq</code>
     */
    public static final Sequence<Long> GAME_STATE_ID_SEQ = Internal.createSequence("game_state_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);
}
