/*
 * This file is generated by jOOQ.
 */
package com.kbalazsworks.tictactoe.db;


import com.kbalazsworks.tictactoe.db.tables.FlywaySchemaHistory;
import com.kbalazsworks.tictactoe.db.tables.Game;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.game</code>.
     */
    public static final Game GAME = Game.GAME;
}
